const weatherIconMapping = {
  1: require('../src/assets/sunny.png'),
  2: require('../src/assets/sunny.png'),
  8: require('../src/assets/sunny.png'),
  9: require('../src/assets/rainy.png'),
  13: require('../src/assets/rainy.png'),
  18: require('../src/assets/rainy.png'),
  25: require('../src/assets/rainy.png'),
  29: require('../src/assets/rainy.png'),
  34: require('../src/assets/rainy.png'),
  48: require('../src/assets/rainy.png'),
  50: require('../src/assets/rainy.png'),
  66: require('../src/assets/rainy.png'),
  68: require('../src/assets/rainy.png'),
  3: require('../src/assets/cloudy.png'),
  6: require('../src/assets/cloudy.png'),
  7: require('../src/assets/cloudy.png'),
  41: require('../src/assets/cloudy.png'),
  42: require('../src/assets/cloudy.png'),
  43: require('../src/assets/cloudy.png'),
  44: require('../src/assets/cloudy.png'),
  63: require('../src/assets/cloudy.png'),
  64: require('../src/assets/cloudy.png'),
  24: require('../src/assets/thunder.png'),
  40: require('../src/assets/thunder.png'),
  11: require('../src/assets/snowy.png'),
  20: require('../src/assets/snowy.png'),
  21: require('../src/assets/snowy.png'),
  27: require('../src/assets/snowy.png'),
  36: require('../src/assets/snowy.png'),
  37: require('../src/assets/snowy.png'),
};
export default weatherIconMapping;